### ISSUE TITLE
delay_ms, us w variables

### ISSUE THREAD

**Issue by someburner** [warrenwoolseyiii/ATMEGA328p_HAL#7]
See the bottom of [this commit](https://github.com/warrenwoolseyiii/ATMEGA328p_HAL/commit/bce0218de194afbd6d028a6a932934658a5f760c)

The built-in _delay_ms + _delay_us macros appear to only be for compile-time constants. So I put a new wrapper that does a for loop, although it's probably a bit more nuanced than that.

**Comment by warrenwoolseyiii** [comment]
@someburner, yes this is a feature that has annoyed me for many years. Unfortunately a wrapper with a for loop is one of the only ways to get around this issue without using compile time constants. Essentially what delay does is insert a bunch of non-ignorable NOP() calls, which is why it needs to have F_CPU defined.

What we could do, is make two different macros for delay functions. One set is traditional, compile time constants like we currently use. The other set, maybe indicated with some prefix like VAR which lets the called know it can use non-compile time constants. So:

```
VAR_DELAY_MS(x) {\
uint32_t I;\
for (I = 0; I < x; I++) DELAY_MS(1);\
}
```

Essentially this code would guarantee a delay of x milliseconds but could possible run longer due to the insertion of add, and compare assembly instructions associated with the for loop.

**Comment by warrenwoolseyiii** [comment]
Issue is now supported in release v1.1.0
